### ISSUE TITLE
styles not working

### ISSUE THREAD

**Issue by Matergi** [Matergi/editorjs-color-picker#1]
workaround, add this style in your app:

```css
.ce-popover--inline .ce-popover--nested .ce-popover__container {
  width: auto !important;
  min-width: unset !important;
}

.ce-popover--inline .ce-popover--nested .ce-popover__items {
  width: max-content;
}
```
